### ISSUE TITLE
Tokio Sync Feature incompatible

### ISSUE THREAD

**Issue by shadowcpy** [jasta/esp32-tokio-demo#1] opened 2023-08-21 20:13 UTC
Hey there,
first of all: thanks for this amazing repo and the effort to make tokio compatible with the ESP-IDF ecosystem.

I may have found a gotcha while experimenting around with the setup:
Enabling and using the `sync` feature in tokio produces linking failures:
```
      /nix/store/s01q3syxbcw426nb6r2jv9034igafy28-esp32-toolchain-20230208/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/bin/ld: /nix/store/s01q3syxbcw426nb6r2jv9034igafy28-esp32-toolchain-20230208/bin/../lib/gcc/riscv32-esp-elf/12.2.0/../../../../riscv32-esp-elf/lib/rv32imc_zicsr_zifencei/ilp32/no-rtti/libc.a(lib_a-fclose.o): in function `_fclose_r':
          /builds/idf/crosstool-NG/.build/riscv32-esp-elf/src/newlib/newlib/libc/stdio/fclose.c:73: warning: pthread_setcancelstate is not implemented and will always fail
       ...
```
probably due to the use of system threads, which need to be patched for linking with ESP-IDF (related https://github.com/ivmarkov/rust-esp32-std-demo/issues/24)

Maybe it is possible to somehow also apply the linker patches to the inner workings of tokio / sync?

The consequence of this incompatibility is that any library depending on sync will fail to build, most prominently `hyper` and subsequently most of the available HTTP Server Frameworks depending on it (axum etc.)

Would be happy to contribute!

**Comment by jasta** [comment] 2023-08-21 20:56
I'm really not sure why the sync feature of tokio in particular would cause anything like this, and I can't reproduce here: https://github.com/jasta/esp32-tokio-demo/tree/sync-test.  Maybe something is wrong with your project set-up?

**Comment by shadowcpy** [comment] 2023-08-21 22:13
Okay yeah, seems really weird. I am gonna look at my setup again.
Getting it to work under NixOS was a pain to start with, maybe there is another mistake in the build chain.
Thanks for the help :+1:

**Comment by jasta** [comment] 2023-08-21 23:25
Ok closing for now, feel free to re-open if you learn more

**Closed as completed by jasta** 2023-08-21 23:25 UTC
Labels: need-info
